name: ONI checks
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  negative:
    permissions:
      contents: read
    uses: Hadden-Industries/markdown-quality/.github/workflows/markdown-quality.yml@47febbe1b6f3282814e77db7ea13eac72b4928ed
    with:
      trusted-repository: MaksymShostak/oxygen-not-included
      trusted-sha: 68bc26b5e465b4c5ed9ca35b00d2510b775dc7ee
      candidate-repository: MaksymShostak/oxygen-not-included
      candidate-sha: ${{ github.sha }}
      profile: .markdown-quality-execution.json
